# curl -X GET --location "http://localhost:5147/api/Restaurants" 
#    -H "Accept: application/json"
GET http://localhost:5147/api/Restaurants
Accept: application/json

###

@local_address = http://localhost:5147

GET {{local_address}}/api/Restaurants
Accept: application/json

###
POST {{local_address}}/api/restaurants
Content-Type:  application/json

{
    "Name": "xxx",
    "Description": "Authentic Indian Restaurant",
    "Category": "Indian",
    "Has Delivery": true,
    "ContactNumber": "1234567",
    "ContactEmail": "x@com",
    "Street": "Pompano",
    "City": "Pompano Beach",
    "State": "FL",
    "Country": "USA",
    "ZipCode": "33484-12"
    
}

###
PATCH {{local_address}}/api/restaurants/1002
Content-Type: application/json

{
  "Name": "Deccan",
  "Description": "Pompano Indian"
}

###
DELETE {{local_address}}/api/restaurants/1007
Content-Type: application/json

###
POST {{local_address}}/api/restaurants/{{restaurantId}}/dishes
Content-Type: application/json
